project:
  type: website
  resources:
    - audio
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!xtra"

website:
  favicon: "assets/gu-logo.png"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Yanjun Chen
      - href: introduction.qmd
        text: Introduction
      - href: source.qmd
        text: Data Sources
      - href: visualization.qmd
        text: Data Visualization
      - href: EDA.qmd
        text: Exploratory Data Analysis
      - href: univariate.qmd
        text: Univariate TS Models (ARIMA/SARIMA)
      - href: multivariate.qmd
        text: Multivariate TS Models (ARIMAX/SARIMAX/VAR)
      - href: financial.qmd
        text: Financial Time Series Models (ARCH/GARCH)
      - href: DL.qmd
        text: Deep Learning for TS
      - href: other.qmd
        text: Other-Interrupted TS/ARFIMA/Spectral Analysis
      - href: conclusion.qmd
        text: Conclusions

format:
  html:
    theme: cosmo
    bibliography:   ./assets/references.bib
    csl:  ./assets/nature.csl
    toc: true



